export const narrationScripts: string[] = [
  "Bonjour et bienvenue ! Aujourd'hui, on met le cap sur ton avenir financier. L'Aide financière aux études, qu'on appelle souvent l'AFE, ça peut sembler compliqué avec toute sa paperasse, mais ne t'inquiète pas. Mon but aujourd'hui est d'expliquer simplement tout ça avec toi en une quinzaine de minutes. On va regarder ensemble comment fonctionnent les prêts et bourses pour que tu puisses te concentrer sur l'essentiel : ta réussite scolaire.",
  "Commençons par la base : quelle est la différence entre un prêt et une bourse ? Le prêt, c'est de l'argent que le gouvernement t'avance. La beauté de la chose, c'est que le gouvernement paie les intérêts à ta place pendant toutes tes études à temps plein. Tu ne commenceras à rembourser que six mois après la fin de tes études, avec un plan adapté à tes moyens. La bourse, par contre, c'est un cadeau ! C'est de l'argent basé sur tes besoins réels que tu n'auras jamais à rembourser. Petit bonus super intéressant : si tu es admissible à une bourse et que tu termines ton programme dans les temps prévus, le gouvernement efface 15 % de ta dette d'études !",
  "Pour avoir droit à l'AFE, il y a trois conditions de base. Premièrement, le statut légal : tu devez être citoyen canadien, résident permanent, ou avoir le statut de personne réfugiée ou protégée. Deuxièmement, la résidence : tu dois résider au Québec au moment de ta demande. Et troisièmement, le programme : tu dois être admis à temps plein en formation professionnelle, au Cégep ou à l'Université. Si vous êtes un étudiant international, des règles spécifiques s'appliquent sur le site de l'aide officielle.",
  "Attention, voici un piège fréquent ! Ne tiens pas pour acquis que toutes les écoles donnent accès à l'aide financière. Si tu vas dans un Cégep public ou un de nos centres de formation professionnelle publics, ton programme est généralement reconnu d'office. Par contre, si tu choisis un collège privé, tu auras droit à l'AFE uniquement si ton programme précis est officiellement reconnu par le Ministère. Vérifie toujours les listes officielles avant de t'inscrire !",
  "Parlons d'indépendance. Normalement, l'AFE prend en compte le revenu de tes parents pour calculer ton aide. Pero si tu es considéré comme autonome, leur salaire ne compte plus du tout ! Pour le devenir, il faut remplir l'un de ces critères : avoir accumulé 24 mois de travail sans étudier à temps plein, détenir 90 crédits universitaires ou un baccalauréat, étudier au cycle supérieur, ou être parent, marié ou enceinte d'au moins 20 semaines. Attention au grand mythe : on ne devient pas autonome automatiquement à 25 ans ! L'âge n'importe pas, seuls ces critères comptent.",
  "Si tu es en situation de handicap ou de troubles d'apprentissage, l'AFE a des mesures d'aide très avantageuses. Avec une déficience fonctionnelle majeure, valide sur présentation de certificat médical, tu as droit à d'excellents avantages : étudier à temps partiel en gardant le statut temps plein et surtout, obtenir une aide versée à 100 % en bourses. Pour les troubles d'apprentissage, le statut à temps plein est aussi préservé, mais l'aide est calculée à taux régulier. N'oublie pas l'allocation pour besoins particuliers qui rembourse les ordinateurs ou logiciels comme Antidote.",
  "La grande question : combien vas-tu recevoir ? Pour l'année 2026-2027, voici les montants mensuels estimés. Si tu habites chez tes parents, le montant théorique de subsistance est d'environ 650 $ par mois. Si tu es logé en appartement, ce montant grimpe à environ 1 387 $ par mois pour t'aider à couvrir l'épicerie, le loyer et tes dépenses de base.",
  "Voici une règle cruciale à anticiper : la résidence réputée. Si ton école est desservie par le transport en commun à partir de la maison de tes parents, l'AFE estime que tu pourrais habiter chez eux. Donc, même si tu décides de louer un appartement près de ton établissement pour ton confort, l'AFE calculera ton aide d'après le montant chez les parents de 650 $ par mois, plutôt que le montant de 1 387 $ pour appartement. Garde bien ceci en tête !",
  "En plus des calculs fondamentaux de chaque mois, sache que l'AFE ajoute d'autres coups de pouce financiers. Tu obtiendras des montants de 231 $ à 500 $ par session pour ton matériel scolaire. Un prêt de 500 $ est disponible spécifiquement pour l'acquisition d'un ordinateur. Il y a aussi des allocations de santé allant jusqu'à 230 $ pour l'opticien tous les deux ans, et des aides pour frais de garde de 207 $ par mois et par enfant.",
  "Comment l'AFE calcule-t-elle tout ça ? C'est équilibré de façon mathématique : ils déterminent les dépenses admises et ils déduisent les contributions financières attendues de ta part, de tes parents ou conjoints. Ce qui reste forme ton besoin financier réel. Sache que la contribution parentale diminue s'il y a d'autres étudiants à charge ou s'ils sont séparés. De plus, tu as pleinement le droit de travailler pendant vos études sans voir ton aide coupée, car une bonne partie de tes revenus est protégée !",
  "Avis important concernant les Bourses Perspective Québec. Ce programme de bourses par session destiné à favoriser certains diplômes ciblés a pris fin. La dernière période d'admission possible pour ces bourses était à l'hiver 2025. Pour ceux qui s'inscrivent à l'automne 2026 ou plus tard, ce soutien n'est malheureusement plus disponible.",
  "Pour bien préparer ta demande, munis-toi de ton code permanent québécois de 12 caractères disponible sur tes relevés d'études, de ton numéro d'assurance sociale, et demande à tes parents ou à ton conjoint de préparer leurs renseignements fiscaux de l'année précédente pour remplir leur déclaration de tiers.",
  "Une fois acceptée, comment l'aide se dépose-t-elle ? Au mois d'août, tu trouveras un certificat de garantie électronique dans ton portail étudiant en ligne. Imprime ce papier précieux et présente-le en personne à ta banque ou ta caisse. C'est l'étape obligatoire pour autoriser l'AFE et le paiement final directement dans ton compte courant chaque mois.",
  "Voici ton calendrier pour l'AFE. Les demandes s'ouvrent dès le mois de mai de chaque année. Fais-la tôt ! Si des documents sont demandés, remets-les au plus vite. Si tu as du retard, tu as jusqu'à 30 jours après la fin de tes études de l'année pour soumettre tes papiers, avec le 29 décembre comme date limite extrême. En hiver, vers janvier ou février, n'oublie pas la confirmation obligatoire de tes revenus d'emploi réels.",
  "Attention au grand danger d'études : l'abandon de cours ou la baisse d'inscriptions. Si tu décides de lâcher un cours en cours de route et que tu descends sous le seuil d'études à temps plein, ton aide financière globale sera coupée d'office. Vos bourses d'études reçues risquent d'être immédiatement converties en prêts à rembourser. Consulter votre API avant d'effectuer un changement !",
  "Tu as des questions ? Sache que tu n'es pas seul à naviguer là-dedans ! Utilise l'aide des bureaux spécialisés de ton Cégep, CFP ou Université, ou sollicite ton conseiller d'orientation à l'école. Tu peux également joindre le service téléphonique de l'AFE au 1-888-345-4505.",
  "Pour conclure, nous t'encourageons fortement à aller faire une simulation en ligne. C'est anonyme, gratuit et très rapide ! Utilise le simulateur sur quebec.ca/afe pour évaluer tes futurs droits."
];
